server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/orclpdb
    username: app_username
    password: app_password
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
HMAC_SECRET: 123