server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    jdbc-url: jdbc:oracle:thin:@//localhost:1521/orclpdb
    username: app_username
    password: app_password
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        type.descriptor.sql.BasicBinder: TRACE
        format_sql: true
logging:
  level:
    org.hibernate:
      sql: DEBUG
      type.descriptor.sql.BasicBinder: TRACE
client:
  datasource:
    jdbc-url: jdbc:oracle:thin:@//localhost:1521/orclpdb
    username: client_username
    password: client_password
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
#    properties:
#      hibernate:
#        temp:
#          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
HMAC_SECRET: 123